USE [master]
GO

/****** Object:  Database [GosPrograms]    Script Date: 02.04.2022 14:32:23 ******/
CREATE DATABASE [GosPrograms]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GosPrograms', FILENAME = N'D:\MSSQL\GosPrograms.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'GosPrograms_log', FILENAME = N'D:\MSSQL\GosPrograms_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GosPrograms].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GosPrograms] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GosPrograms] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GosPrograms] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GosPrograms] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GosPrograms] SET ARITHABORT OFF 
GO

ALTER DATABASE [GosPrograms] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GosPrograms] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GosPrograms] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GosPrograms] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GosPrograms] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GosPrograms] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GosPrograms] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GosPrograms] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GosPrograms] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GosPrograms] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GosPrograms] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GosPrograms] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GosPrograms] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GosPrograms] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GosPrograms] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GosPrograms] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GosPrograms] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GosPrograms] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GosPrograms] SET  MULTI_USER 
GO

ALTER DATABASE [GosPrograms] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GosPrograms] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GosPrograms] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GosPrograms] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GosPrograms] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GosPrograms] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GosPrograms] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GosPrograms] SET  READ_WRITE 
GO

