//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract_()
        {
            this.Invoice_ = new HashSet<Invoice_>();
        }
    
        public int Contract_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> DepositPayed { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<decimal> ContractTotalPrice { get; set; }
        public Nullable<decimal> ContracTotalPrice_inclVAT { get; set; }
        public string ProductionProcess { get; set; }
    
        public virtual Order_ Order_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_> Invoice_ { get; set; }
    }
}
