//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_()
        {
            this.Order_ = new HashSet<Order_>();
        }
    
        public int Customer_ID { get; set; }
        public string FistName { get; set; }
        public string FamilyName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string OrganisationName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string email { get; set; }
        public string Phone { get; set; }
        public string IDNumber { get; set; }
        public string IDDocumentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_> Order_ { get; set; }
    }
}
