//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails_
    {
        public int Detail_ID { get; set; }
        public Nullable<int> Accessory_ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
    
        public virtual Accessory_ Accessory_ { get; set; }
        public virtual Order_ Order_ { get; set; }
    }
}
