//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR_Kuzntecov_N.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subroutines
    {
        public int idSubroutines { get; set; }
        public string name { get; set; }
        public Nullable<int> idGosProg { get; set; }
    
        public virtual GosProgram GosProgram { get; set; }
    }
}
