//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int comment_id { get; set; }
        public int news_id { get; set; }
        public string text_comment { get; set; }
        public Nullable<System.DateTime> date_make { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public int user_id { get; set; }
    
        public virtual News News { get; set; }
        public virtual Users Users { get; set; }
    }
}
