//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc()
        {
            this.KR2 = new HashSet<KR2>();
        }
    
        public int id_Doc { get; set; }
        public Nullable<int> id_debtor { get; set; }
        public string name_doc { get; set; }
        public string number_doc { get; set; }
        public Nullable<System.DateTime> date_doc { get; set; }
        public Nullable<System.DateTime> date_doc_to_KR2 { get; set; }
    
        public virtual Debtors Debtors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KR2> KR2 { get; set; }
    }
}
